### ISSUE TITLE
TODO: Test QuicStream

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#291]
JavaScript Side:

* [ ] Verify opening a stream (all options, failure and success conditions)
* [ ] Verify stream ID, origin, and direction indictions
* [ ] Verify client side stream minimally usable before connection is ready (ability to buffer writees). Verify that functions unavailable before connection is ready fail appropriately.
* [ ] Verify proper emission of QuicStream events
* [ ] Verify write and end callbacks are called appropriately
* [ ] Verify state fields (e.g. pending, aborted, destroyed, etc) are reporting as expected
* [ ] Verify QuicStream statistics and histograms
* [ ] Verify appropriate and consistent destroy flow
* [ ] Verify sendFile/sendFD working appropriately
* [ ] Verify write working appropriately
* [ ] Verify sending informational, initial, and trailing headers (HTTP/3 only)
* [ ] Verify push streams (HTTP/3 only)

C++ Side
* [ ] Verify QuicBuffer-based data buffering and callbacks
* [ ] Verify QuicBuffer-based data flow to QUIC
* [ ] Verify inbound data flow
* [ ] Verify Stream Reset and Stream Close appropriately handled

**Comment by addaleax** [comment]
@jasnell For items like

> Verify sendFile/sendFD working appropriately

Are those things that can already be crossed off, given that there are tests for this?

**Comment by jasnell** [comment]
Yes, this is really an audit list. We need to go through the existing tests to make sure they provide proper coverage, but if they do, feel free to check off
