### ISSUE TITLE
Current Checklist of stuff to do

### ISSUE THREAD

**Issue by jasnell** [nodejs/quic#45]
Just to give folks an idea of the full list of things still being worked on:

# Procedural
  * [x] Convert this checklist into a project board
  * [ ] Open PR on nodejs/node adding initial QUIC implementation behind the configure switch
# Functional
* Build
  * [ ] Implement configure build switch to optionally enable building QUIC support
* Error Handling
  * [ ] QuicSession HandleError is broken in some scenarios. Causes a segfault. Need to investigate where and when
  * [ ] Connection timeout https://github.com/nodejs/quic/issues/39
  * [ ] Ensure proper handling and use of QUIC session and crypto error codes
  * [ ] When out of packet numbers error occurs, we may want implement a special error for this so that this case can be detected.
  * [ ] Need to figure out how to *test* various error edge cases (such as out of packet number errors)
* Memory
  * [ ] Fill out memory tracking
  * [ ] Use stack allocated packet buffers rather than malloced if possible
* Socket/Session/Stream Lifecycle
* Protocol
  * [ ] Ensure that retransmission is occurring properly. In general, packets are being retransmitted but dropped packets having a fairly significant cost currently. Retransmission can be more efficient and needs to be looked at in detail.
  * [ ] Ensure that path validation is occurring correctly and is tested
  * [ ] Implement ability to optionally send stateless reset. This is going to be a bit tricky. An endpoint sends a stateless reset when it does not have access to connection state any longer, but that means we need to keep track of CID's and their corresponding stateless reset tokens in way that can survive a crash. But we don't want to keep them around forever.
  * [ ] Ensure that moving to a server preferred address and migration to a new connection can actually happen simultaneously
  * [ ] Complete support for server preferred address. Upon receiving and validating a server preferred address, client should migrate to the preferred address automatically.
  * [ ] Currently, in most cases, setting stream fin requires an empty stream frame with fin bit set. See if we can optimize that further
  * [ ] Make use of final size parameter when known (at the very least, there should be a getter on the QuicStream)
  * [ ] Wait for NEW_TOKEN support to be implemented by ngtcp2
  * [ ] The basic API for sending SERVER_BUSY responses is in place but ngtcp2 does not yet fully support sending CONNECTION_CLOSE frames in Initial packets. Until that is implemented, the SERVER_BUSY implementation is disabled and the test is not yet completely implemented. (Update: I *believe* landing https://github.com/nodejs/quic/pull/54 will provide the necessary support for sending CONNECTION_CLOSE in an initial packet)
* Security
  * [ ] Implement various slow loris style DOS mitigations
  * [ ] Verify amplification attack mitigations
* Performance Tracking
  * [ ] Implement the JavaScript side of the perf tracking histograms
* Features
  * [ ] Implement QuicSocket proxy mode. This will allow received packet headers to be intercepted and forwarded on to a separate QuicSocket instance, allowing a Node.js instance to be used as a QUIC passthrough.

# Optional/Lower Priority

* [ ] Eventually, we will want to implement support for receiving and validating ICMP packet too big messages as a mechanism for detecting failures in QUIC packet transmission due to MTU packet size.
* [ ] Determine whether we want to support zero-length connection IDs. This is optional by the specification. It's not yet clear how ngtcp2 supports zero-length connection IDs. Need to test.
* [ ] Revisit the flow control / backpressure strategy. We may want to allow multiple flow control strategies to allow performance to be tuned.
* [ ] openStream() API ... specifically, ability to specify an initial chunk of data to include when opening the stream.

# Completed:
* [x] Connection migration test is currently broken, need to verify that it's working and ensure completed implementation PR: https://github.com/nodejs/quic/pull/50
* [x] Ensure that all C++ objects can be destroyed immediately in the current callstack without requiring nextTick or setImmediate deferral.
* [x] Ensure application close on QuicSessions
* [x] Ensure that close and destroy are re-entrant tolerant
* [x] Catch out of packet numbers error. The code will do a SilentClose.
* [x] Only prefer address validation once per connection per address? Make this configurable https://github.com/nodejs/quic/pull/48/files
* [x] Verify that retransmissions are happening correctly. Update: regular stream retransmissions are happening as necessary but handshake is still iffy.
* [x] Verify that STREAM_RESET and STOP_SENDING are handled appropriately
* [x] Improve handling of configuration and transport params
* [x] Implement exponential backoff on the sending of CONNECTION_CLOSE frames during closing period.
* [x] Ensure that STOP_SENDING is not sent after receiving a STREAM_RESET from the peer
* [x] Ensure that only CONNECTION_CLOSE frames are sent in the closing state, Ensure that absolutely no frames in the draining state.
* [x] Verify how sending of version negotiation packets is handled. e.g. are they sent for 0RTT packets? 
* [x] Ensure that crypto handshake buffer protections are working
* [x] Implement handling when valid stateless reset is received
* [x] QUIC recommends using path maximum transmission unit discovery but libuv and Node.js currently provide no way of implementing this. We should revisit this at some point later but for now, we cannot support PMTUD.
* [x] Determine if we want to support latency spin bit in any way? ngtcp2 currently does not expose an API for dealing with the spin bit. Nor does it expose the necessary information we need to implement it properly ourselves. Therefore, until ngtcp2 supports it, we won't support it.
* [x] Determine how and if we ever want to support multiple QUIC protocol versions. Update: for now, we're only going to support one QUIC protocol version at a time because that's what ngtcp2 is limited to.
* [x] Ensure that a server completely ignores invalid or unexpected frames
* [x] alpn is absolutely required so ensure that it's always there. Error if not provided
* [x] Verify stream commitment attack mitigations
* [x] Avoid stream commitment attacks. Verify that implicitly opened streams do not commit resources unless data is actually sent.
* [x] We need an API to trigger a key update
* [x] ~~Implementing a pool of connection IDs to make generation more efficient~~ Determined there's no performance advantage realized by this relative to the cost of implementation
* [x] ~~Determine if there's any reason to expose an API for ping frames. Determine how we could ever support responses.~~ For the time being, there's no reason for us to support PING frames directly. ngtcp2 uses them as it determines it is necessary and there are ways we can monitor the aliveness and round trip times without a dedicated ping API.
* [x] ~~Determine if there's any way to support extension frames with ngtcp2~~. ngtcp2 currently does not expose any API we can use to encode or decode extension frames. Until it does, there's nothing we can really do to support them.
* [x] ~~Determine whether we want to expose an API to force a QuicSession to use a new connection ID. Changing the CID is permitted by the specification, we just need to decide whether to expose an API for it. Use of such an API won't be common but there is an argument to be made about having it available for privacy/security reasons.~~ ngtcp2 currently does not provide an API for supporting this. So until it does, there's nothing to do.
* [x] ~~Determine api for supporting extension transport parameters~~ ngtcp2 currently does not support the ability to use extension transport params. So until it does, there's nothing to do.
* [x] ~~Verify ngtcp2 support for ECN~~ libuv currently does not provide access to the ECN bit for UDP, making it impossible for us to support use of ECN at the current time.
* [x] ~~Determine whether we should allow disabling the idle timeout at all. There are many reasons why we shouldn't allow disabling it.~~ We're not going to allow disabling the idle timeout at the current time. There are too many reasons to have it there. A user who really wants to can set the timeout to a very large value.

**Comment by splitice** [comment]
draft-22 has a new 32bit sizing issue:

```
error: ‘void node::quic::QuicSession::SetLastError(node::quic::QuicErrorFamily, int)’ cannot be overloaded with ‘void node::quic::QuicSession::SetLastError(node::quic::QuicErrorFamily, ssize_t)’
```

**Comment by jasnell** [comment]
@splitice ... https://github.com/nodejs/quic/pull/46

**Comment by amiiigh** [comment]
Hey
Is there like a getting started on this repo anywhere?
it seems like I can't find any 
I would appreciate any help 
Thanks

**Comment by jasnell** [comment]
@amiiigh ... if you're referring specifically to using the QUIC implementation, I would hold off for the time being unless you're willing for things to be a bit breaky still. Also, TLS is built-in and required by QUIC... there's no way to turn it off.

**Comment by jasnell** [comment]
Closing this issue as I've converted all of the todo items into a project board
